### ISSUE TITLE
DEFAULT FORMATTER CRASHED- cant make more than ~180 connections? 

### ISSUE THREAD

**Issue by Ashtonian** [emqx/emqtt-bench#103]
macOS Big Sur 11.2 on intel i9
running latest versions

```sh
brew install erlang 
erl # Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]
git clone https://github.com/emqx/emqtt-bench.git 
cd ./emqtt_bench/
make 
./emqtt_bench conn -u ** -P ** -h mqtt.mydomain.com -p 1883 -c 50000 

#DEFAULT FORMATTER CRASHED connected: 187DEFAULT FORMATTER CRASHED
```

If I run multiple instances of the tool, each one establishes about 180-200 connections and then starts to print that error. Please help. mqtt.mydomain.com is a 3 node cluster behind an elb that seems to be working correctly. Admin detects ~200 ish clients and can see all 3 nodes.

**Comment by Ashtonian** [comment]
needed to run `ulimit -n 100000` in the shell session of emqtt_bench otherwise the client couldn't make many connections that it needed. Was able to make 5-10k connections to a 3 node emqx cluster before it complained about i/o on my local machine, moved it to a m5.xlarge and was able to get to ~20k connections before getting `client(21765): connect error - eaddrinuse` on the benchmark client which I think is a client sizing issue still. I then spun up another m5.xlarge and was able to get another 10k connections to our 3 node cluster so total ~30-36k connections but then started to get exit shutdown,tcp_closed. still looking into that further. closing as thats a separate issue.

**Comment by LobsterMan** [comment]
> ulimit -n 100000

Thanks. I had the same issue, that solved it
