### ISSUE TITLE
connect error - ehostunreach

### ISSUE THREAD

**Issue by puzc1993** [emqx/emqtt-bench#108]
./emqtt_bench sub -h XX.XX.XX.XX -p 1883 -c 50000 -i 10 -t bench/%i -q 2
client(100000): connect error - ehostunreach
client(99997): connect error - ehostunreach
client(99999): connect error - ehostunreach
client(99998): connect error - ehostunreach
client(99996): connect error - ehostunreach
client(99995): connect error - ehostunreach

我用公共broker试了下，结果是
/emqtt_bench sub -h broker.emqx.io -p 1883 -c 50000 -i 10 -t bench/%i -q 2
connected: 688^C

我自己的broker=>
./emqx_ctl status
Node 'emqx@127.0.0.1' is started
emqx 4.2.10 is running

**Comment by HJianBo** [comment]
It looks like the network is not working. Is there a firewall off or something?

Try running the `telnet` command on the emqtt-bench machine to test if you can connect to the emqx service

**Comment by puzc1993** [comment]
多谢！firewalld开启后没有开放mqtt相应端口，开放后可以访问了！
