### ISSUE TITLE
The compilation is successful, but the execution reports an error

### ISSUE THREAD

**Issue by yilezhu** [emqx/emqtt-bench#113]
The compilation is successful, but the execution reports an error.My running script is as follows
` ./emqtt_bench pub -h 192.168.1.118 -p 1883 -V 5 -c 200 -u admin -P 123456 -i 10 -I 200 -s 102400 -t test/data/200a5a100kb
`

error ：
![image](https://user-images.githubusercontent.com/18655233/120502003-a3a70280-c3f4-11eb-8f90-d1e334a82d2c.png)

=ERROR REPORT==== 2-Jun-2021::22:36:35.770971 ===
Error in process <0.299.0> with exit value:
{function_clause,[{dtls_v1,corresponding_tls_version,
                           ['tlsv1.3'],
                           [{file,"dtls_v1.erl"},{line,55}]},
                  {dtls_v1,all_suites,1,[{file,"dtls_v1.erl"},{line,41}]},
                  {ssl,cipher_suites,2,[{file,"ssl.erl"},{line,909}]},
                  {emqtt_bench,'-all_ssl_ciphers/0-lc$^0/1-0-',1,
                               [{file,"/root/emqtt-bench/src/emqtt_bench.erl"},
                                {line,538}]},
                  {emqtt_bench,'-all_ssl_ciphers/0-lc$^0/1-0-',1,
                               [{file,"/root/emqtt-bench/src/emqtt_bench.erl"},
                                {line,538}]},
                  {emqtt_bench,all_ssl_ciphers,0,
                               [{file,"/root/emqtt-bench/src/emqtt_bench.erl"},
                                {line,538}]},
                  {emqtt_bench,ssl_opts,2,
                               [{file,"/root/emqtt-bench/src/emqtt_bench.erl"},
                                {line,528}]},
                  {emqtt_bench,connect,4,
                               [{file,"/root/emqtt-bench/src/emqtt_bench.erl"},
                                {line,376}]}]}

=ERROR REPORT==== 2-Jun-2021::22:36:35.781980 ===
Error in process <0.300.0> with exit value:
{function_clause,[{dtls_v1,corresponding_tls_version,
                           ['tlsv1.3'],
                           [{file,"dtls_v1.erl"},{line,55}]},
                  {dtls_v1,all_suites,1,[{file,"dtls_v1.erl"},{line,41}]},
                  {ssl,cipher_suites,2,[{file,"ssl.erl"},{line,909}]},
                  {emqtt_bench,'-all_ssl_ciphers/0-lc$^0/1-0-',1,
                               [{file,"/root/emqtt-bench/src/emqtt_bench.erl"},
                                {line,538}]},
                  {emqtt_bench,'-all_ssl_ciphers/0-lc$^0/1-0-',1,
                               [{file,"/root/emqtt-bench/src/emqtt_bench.erl"},
                                {line,538}]},
                  {emqtt_bench,all_ssl_ciphers,0,
                               [{file,"/root/emqtt-bench/src/emqtt_bench.erl"},
                                {line,538}]},
                  {emqtt_bench,ssl_opts,2,
                               [{file,"/root/emqtt-bench/src/emqtt_bench.erl"},
                                {line,528}]},
                  {emqtt_bench,connect,4,
                               [{file,"/root/emqtt-bench/src/emqtt_bench.erl"},
                                {line,376}]}]}

^C
[root@node01 emqtt-bench]# ^C

**Comment by k32** [comment]
Which version of Erlang/OTP are you using? Can you try running it on OTP23?

**Comment by yilezhu** [comment]
Yes, because my computer has installed a lower version, I need to uninstall the lower version and then re install the higher version

**Comment by yilezhu** [comment]
@k32 Hello, friend, what's the unit of - s? b or kb?  
`-s 102400` Does it mean that 100kb?

**Comment by k32** [comment]
@yilezhu It's in bytes.
