### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by wangcongzhen** [emqx/emqtt-bench#116]
[root@hecs-x-xlarge-2-linux-20210531180637 soft]# cd emqtt-bench-master
[root@hecs-x-xlarge-2-linux-20210531180637 emqtt-bench-master]# make
/soft/emqtt-bench-master/rebar3 unlock
/soft/emqtt-bench-master/rebar3 compile
===> Verifying dependencies...
===> Fetching emqtt (from {git,"https://github.com/emqx/emqtt",{tag,"1.4.0"}})
===> Fetching getopt v1.0.1
===> Fetching cowlib v2.11.0
===> Skipping getopt v1.0.2 as an app of the same name has already been fetched
===> Fetching gun (from {git,"https://github.com/emqx/gun",{tag,"1.3.4"}})
===> Failed to fetch and copy dep: {git,"https://github.com/emqx/gun",
                                   {tag,"1.3.4"}}
make: *** [compile] Error 1
[root@hecs-x-xlarge-2-linux-20210531180637 emqtt-bench-master]# ^C
[root@hecs-x-xlarge-2-linux-20210531180637 emqtt-bench-master]#

**Comment by k32** [comment]
Hello,

I cannot reproduce this issue on the `master` branch. I also verified that 1.3.4 tag exists in emqx/gun repo.
Could you check that you can clone the git repo?
`git clone "https://github.com/emqx/gun"`

**Comment by wangcongzhen** [comment]
[root@hecs-x-xlarge-2-linux-20210531180637 soft]# git clone "https://github.com/emqx/gun"
Cloning into 'gun'...
remote: Enumerating objects: 3593, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
error: RPC failed; curl 56 TCP connection reset by peer
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by k32** [comment]
Hello,

You're having network problems, or maybe your git binary is outdated. Try to update your git and clone this repo over a different network.
