### ISSUE TITLE
build faild

### ISSUE THREAD

**Issue by ferrisz** [emqx/emqtt-bench#118]
```
[root@VM-4-11-centos emqtt-bench]# make
/root/emqtt-bench/rebar3 unlock
/root/emqtt-bench/rebar3 compile
===> Verifying dependencies...
===> Fetching emqtt (from {git,"https://github.com/emqx/emqtt",{tag,"1.4.0"}})
===> Fetching getopt v1.0.1
===> Fetching cowlib v2.11.0
===> Skipping getopt v1.0.2 as an app of the same name has already been fetched
===> Fetching gun (from {git,"https://github.com/emqx/gun",{tag,"1.3.4"}})
===> Fetching quicer (from {git,"https://github.com/emqx/quic",{tag,"0.0.3"}})
===> Skipping cowlib (from {git,"https://github.com/ninenines/cowlib","2.8.0"}) as an app of the same name has already been fetched
子模组 'submodules/msquic'（https://github.com/microsoft/msquic.git）已对路径 'submodules/msquic' 注册
正克隆到 '/root/emqtt-bench/_build/default/lib/quicer/submodules/msquic'...
子模组路径 'submodules/msquic'：检出 '3be5c66bd488767b77ddfa2aa439c93797ce4437'
子模组 'submodules/googletest'（https://github.com/google/googletest）已对路径 'submodules/msquic/submodules/googletest' 注册
子模组 'submodules/openssl'（https://github.com/quictls/openssl.git）已对路径 'submodules/msquic/submodules/openssl' 注册
子模组 'submodules/wil'（https://github.com/microsoft/wil）已对路径 'submodules/msquic/submodules/wil' 注册
正克隆到 '/root/emqtt-bench/_build/default/lib/quicer/submodules/msquic/submodules/googletest'...
正克隆到 '/root/emqtt-bench/_build/default/lib/quicer/submodules/msquic/submodules/openssl'...
正克隆到 '/root/emqtt-bench/_build/default/lib/quicer/submodules/msquic/submodules/wil'...
子模组路径 'submodules/msquic/submodules/googletest'：检出 'e8512bc38c4c0060858c3306b0660a3f126aee30'
子模组路径 'submodules/msquic/submodules/openssl'：检出 'a6e9d76db343605dae9b59d71d2811b195ae7434'
子模组 'boringssl'（https://boringssl.googlesource.com/boringssl）已对路径 'submodules/msquic/submodules/openssl/boringssl' 注册
子模组 'krb5'（https://github.com/krb5/krb5）已对路径 'submodules/msquic/submodules/openssl/krb5' 注册
子模组 'pyca.cryptography'（https://github.com/pyca/cryptography.git）已对路径 'submodules/msquic/submodules/openssl/pyca-cryptography' 注册
正克隆到 '/root/emqtt-bench/_build/default/lib/quicer/submodules/msquic/submodules/openssl/boringssl'...
正克隆到 '/root/emqtt-bench/_build/default/lib/quicer/submodules/msquic/submodules/openssl/krb5'...
正克隆到 '/root/emqtt-bench/_build/default/lib/quicer/submodules/msquic/submodules/openssl/pyca-cryptography'...
子模组路径 'submodules/msquic/submodules/openssl/boringssl'：检出 '2070f8ad9151dc8f3a73bffaa146b5e6937a583f'
子模组路径 'submodules/msquic/submodules/openssl/krb5'：检出 '890ca2f401924cdcb88f493950b04700bbe52db3'
子模组路径 'submodules/msquic/submodules/openssl/pyca-cryptography'：检出 '09403100de2f6f1cdd0d484dcb8e620f1c335c8f'
子模组路径 'submodules/msquic/submodules/wil'：检出 '86353933d5fba0caf61503c8b09e10e182dccdfb'
CMake Error: The source directory "/root/emqtt-bench/_build/default/lib/quicer/c_build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
===> Hook for compile failed!

make: *** [compile] 错误 1
```

**Comment by fcofabricio** [comment]
Same issue

**Comment by qzhuyan** [comment]
| ===> Fetching quicer (from {git,"https://github.com/emqx/quic",{tag,"0.0.3"}})

@ferrisz  looks like you are using old quicer 0.0.3

pls retry with latest branch

**Comment by tjangdra** [comment]
I have the same issue not able to build the application today from my Ubuntu 18.

emqx@ubuntu:~$` erl
Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Eshell V12.0  (abort with ^G)
1> 
User switch command
 --> q
emqx@ubuntu:~$ git clone https://github.com/emqx/emqtt-bench.git
Cloning into 'emqtt-bench'...
remote: Enumerating objects: 476, done.
remote: Counting objects: 100% (231/231), done.
remote: Compressing objects: 100% (137/137), done.
remote: Total 476 (delta 125), reused 169 (delta 81), pack-reused 245
Receiving objects: 100% (476/476), 2.34 MiB | 9.19 MiB/s, done.
Resolving deltas: 100% (259/259), done.
emqx@ubuntu:~$ cd emqtt-bench/
emqx@ubuntu:~/emqtt-bench$ make
/home/emqx/emqtt-bench/rebar3 unlock
/home/emqx/emqtt-bench/rebar3 compile
===> Verifying dependencies...
===> Fetching emqtt (from {git,"https://github.com/emqx/emqtt",{tag,"1.4.0"}})
===> Fetching getopt v1.0.1
===> Fetching cowlib v2.11.0
===> Skipping getopt v1.0.2 as an app of the same name has already been fetched
===> Fetching gun (from {git,"https://github.com/emqx/gun",{tag,"1.3.4"}})
===> Fetching quicer (from {git,"https://github.com/emqx/quic",{tag,"0.0.3"}})
===> Skipping cowlib (from {git,"https://github.com/ninenines/cowlib","2.8.0"}) as an app of the same name has already been fetched
Submodule 'submodules/msquic' (https://github.com/microsoft/msquic.git) registered for path 'submodules/msquic'
Cloning into '/home/emqx/emqtt-bench/_build/default/lib/quicer/submodules/msquic'...
Submodule path 'submodules/msquic': checked out '3be5c66bd488767b77ddfa2aa439c93797ce4437'
Submodule 'submodules/googletest' (https://github.com/google/googletest) registered for path 'submodules/msquic/submodules/googletest'
Submodule 'submodules/openssl' (https://github.com/quictls/openssl.git) registered for path 'submodules/msquic/submodules/openssl'
Submodule 'submodules/wil' (https://github.com/microsoft/wil) registered for path 'submodules/msquic/submodules/wil'
Cloning into '/home/emqx/emqtt-bench/_build/default/lib/quicer/submodules/msquic/submodules/googletest'...
Cloning into '/home/emqx/emqtt-bench/_build/default/lib/quicer/submodules/msquic/submodules/openssl'...
Cloning into '/home/emqx/emqtt-bench/_build/default/lib/quicer/submodules/msquic/submodules/wil'...
Submodule path 'submodules/msquic/submodules/googletest': checked out 'e8512bc38c4c0060858c3306b0660a3f126aee30'
Submodule path 'submodules/msquic/submodules/openssl': checked out 'a6e9d76db343605dae9b59d71d2811b195ae7434'
Submodule 'boringssl' (https://boringssl.googlesource.com/boringssl) registered for path 'submodules/msquic/submodules/openssl/boringssl'
Submodule 'krb5' (https://github.com/krb5/krb5) registered for path 'submodules/msquic/submodules/openssl/krb5'
Submodule 'pyca.cryptography' (https://github.com/pyca/cryptography.git) registered for path 'submodules/msquic/submodules/openssl/pyca-cryptography'
Cloning into '/home/emqx/emqtt-bench/_build/default/lib/quicer/submodules/msquic/submodules/openssl/boringssl'...
Cloning into '/home/emqx/emqtt-bench/_build/default/lib/quicer/submodules/msquic/submodules/openssl/krb5'...
Cloning into '/home/emqx/emqtt-bench/_build/default/lib/quicer/submodules/msquic/submodules/openssl/pyca-cryptography'...
Submodule path 'submodules/msquic/submodules/openssl/boringssl': checked out '2070f8ad9151dc8f3a73bffaa146b5e6937a583f'
Submodule path 'submodules/msquic/submodules/openssl/krb5': checked out '890ca2f401924cdcb88f493950b04700bbe52db3'
Submodule path 'submodules/msquic/submodules/openssl/pyca-cryptography': checked out '09403100de2f6f1cdd0d484dcb8e620f1c335c8f'
Submodule path 'submodules/msquic/submodules/wil': checked out '86353933d5fba0caf61503c8b09e10e182dccdfb'
sh: 1: exec: cmake: not found
===> Hook for compile failed!

make: *** [Makefile:10: compile] Error 1
emqx@ubuntu:~/emqtt-bench$




> | ===> Fetching quicer (from {git,"[https://github.com/emqx/quic",{tag,"0.0.3"}}](https://github.com/emqx/quic%22,%7Btag,%220.0.3%22%7D%7D))
> 
> @ferrisz looks like you are using old quicer 0.0.3
> 
> pls retry with latest branch

**Comment by qzhuyan** [comment]
@tjangdra 
You don't have cmake installed, cmake is used for compiling QUIC support, in case you don't want QUIC support
you can change the emqtt version to `1.4.3` in rebar.config and then 

```
export BUILD_WITHOUT_QUIC=1
make clean
make
```
