### ISSUE TITLE
libquicer_nif.so: cannot open shared object file: No such file or directory'

### ISSUE THREAD

**Issue by TranManhCuong2368** [emqx/emqtt-bench#124]
Hi, I have met an issue when run "  ./emqtt_bench conn -c 50000 -i 10":
=ERROR REPORT==== 2-Oct-2021::18:13:50.940390 ===
Error in process <0.84.0> on node 'emqtt_bench-340@localhost' with exit value:
{{badmatch,{error,{load_failed,"Failed to load NIF library: '/data/emqtt-bench/libquicer_nif.so: cannot open shared object file: No such file or directory'"}}},
 [{quicer_nif,init,0,
              [{file,"/data/emqtt-bench/_build/default/lib/quicer/src/quicer_nif.erl"},
               {line,49}]},
  {code_server,'-handle_on_load/5-fun-0-',1,
               [{file,"code_server.erl"},{line,1340}]}]}

=WARNING REPORT==== 2-Oct-2021::18:13:50.941440 ===
The on_load function for module quicer_nif returned:
{{badmatch,{error,{load_failed,"Failed to load NIF library: '/data/emqtt-bench/libquicer_nif.so: cannot open shared object file: No such file or directory'"}}},
 [{quicer_nif,init,0,[{file,...},{...}]},
  {code_server,'-handle_on_load/5-fun-0-',1,[{...}|...]}]}

=CRASH REPORT==== 2-Oct-2021::18:13:50.941478 ===
  crasher:
    initial call: application_master:init/4
    pid: <0.82.0>
    registered_name: []
    exception exit: {bad_return,
                     {{quicer_app,start,[normal,[]]},
                      {'EXIT',
                       {undef,
                        [{quicer_nif,open_lib,[],[]},
                         {quicer_app,start,2,
                          [{file,
                            "/data/emqtt-bench/_build/default/lib/quicer/src/quicer_app.erl"},
                           {line,24}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,277}]}]}}}}
      in function  application_master:init/4 (application_master.erl, line 138)
    ancestors: [<0.81.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.83.0>,normal}]
    links: [<0.81.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 237
  neighbours:

=INFO REPORT==== 2-Oct-2021::18:13:50.959876 ===
    application: quicer
    exited: {bad_return,
                {{quicer_app,start,[normal,[]]},
                 {'EXIT',
                     {undef,
                         [{quicer_nif,open_lib,[],[]},
                          {quicer_app,start,2,
                              [{file,
                                   "/data/emqtt-bench/_build/default/lib/quicer/src/quicer_app.erl"},
                               {line,24}]},
                          {application_master,start_it_old,4,
                              [{file,"application_master.erl"},
                               {line,277}]}]}}}}
    type: temporary
escript: exception error: no match of right hand side value 
                 {error,
                  {quicer,
                   {bad_return,
                    {{quicer_app,start,[normal,[]]},
                     {'EXIT',
                      {undef,
                       [{quicer_nif,open_lib,[],[]},
                        {quicer_app,start,2,
                         [{file,
                           "/data/emqtt-bench/_build/default/lib/quicer/src/quicer_app.erl"},
                          {line,24}]},
                        {application_master,start_it_old,4,
                         [{file,"application_master.erl"},{line,277}]}]}}}}}}
  in function  emqtt_bench:prepare/0 (/data/emqtt-bench/src/emqtt_bench.erl, line 264)
  in call from emqtt_bench:start/2 (/data/emqtt-bench/src/emqtt_bench.erl, line 229)
  in call from escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3

**Comment by k32** [comment]
Have you built emqtt_bench from source? It looks like some dependencies weren't built. Could you share the build log?
If you don't need to test MQTT over QUIC feature, you can try using `0.3.3` tag as a quick workaround, I think it doesn't require QUIC.

**Comment by TranManhCuong2368** [comment]
Hi @qzhuyan, so how can I take libquicer_nif.so ? I mean where is it? Because I tried to search it on google, but no information :(
