### ISSUE TITLE
make 有问题

### ISSUE THREAD

**Issue by wupxu** [emqx/emqtt-bench#141]
make: execvp: /*/*/emqtt-bench-master/rebar3: 权限不够
make: *** [unlock] 错误 127

**Comment by qzhuyan** [comment]
Could you describe your env?

**Comment by wupxu** [comment]
系统：centos7

**Comment by wupxu** [comment]
现在出现了新的问题：
[root**  emqtt-bench-master]# make
/data/emqtt-bench-master/rebar3 unlock
/data/emqtt-bench-master/rebar3 compile
===> Verifying dependencies...
===> Failed to update package getopt from repo hexpm
===> Package not found in any repo: getopt 1.0.1
make: *** [compile] 错误 1

**Comment by lic0914** [comment]
OS: Ubuntu 20.04 
``` bash
>$ where is make
make: /usr/bin/make /usr/share/man/man1/make.1.gz
>$ make
/usr/bin/env: ‘bash\r’: No such file or directory
make: *** [Makefile:35: ensure-rebar3] Error 127
```
