### ISSUE TITLE
make error，Failed to fetch and copy dep

### ISSUE THREAD

**Issue by wttt-py** [emqx/emqtt-bench#148]
![err](https://user-images.githubusercontent.com/83765757/154185103-9d8ed774-3eee-4477-8eb3-fac0a9d53134.png)
please check it~ thanks

**Comment by HJianBo** [comment]
This seems to be a network issue, you just need to make sure you can clone the emqx/quic repository.

Or compile without quic:
```
BUILD_WITHOUT_QUIC=1 make
```

**Comment by wttt-py** [comment]
thanks， compile without quic is ok
