### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by rkkilari** [emqx/emqtt-bench#171]
I am using esl-erlang_22.3.4.9-1 on WSL2.

When I run make I get below error

===> Compiling quicer
===> Analyzing applications...
===> Compiling emqtt_bench
===> Compiling src/emqtt_bench.erl failed
src/emqtt_bench.erl:493: syntax error before: _000

src/emqtt_bench.erl:477: function run/6 undefined

src/emqtt_bench.erl:950: function shard_addr/2 is unused

make: *** [Makefile:12: compile] Error 1

**Comment by qzhuyan** [comment]
We have dropped support of otp22.

**Comment by qzhuyan** [comment]
~~We have dropped support of otp22.~~

Sorry I misread it .
