### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by CYCHEN97** [emqx/emqtt-bench#187]
![image](https://user-images.githubusercontent.com/61934856/184123694-66b45959-764d-4502-91ca-d7d1ea835458.png)
请问怎么解决？

**Comment by qzhuyan** [comment]
Pls try use otp24 to compile then.

**Comment by CYCHEN97** [comment]
> Pls try use otp24 to compile then.
![image](https://user-images.githubusercontent.com/61934856/184272598-5995c404-d84a-46cb-ac79-0233f3c02533.png)
换成otp24去编译就可以了，谢谢大佬指点
