### ISSUE TITLE
Cannot pull the emqtt-bench image from dockerhub

### ISSUE THREAD

**Issue by jumpingliu** [emqx/emqtt-bench#193]
I'm using docker to build emqtt-bench image and complete the prequisite steps (clone the repo and follow [this](https://github.com/emqx/emqtt-bench/blob/master/README_FOR_DOCKER.md))
When I tried to pull the emqtt-bench image from dockerhub, it keeps failing as follows,

`$docker run -it emqtt_bench conn -c 50000 -i 10`
`Unable to find image 'emqtt_bench:latest' locally
docker: Error response from daemon: pull access denied for emqtt_bench, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
`

After `$docker login `succeed, it still cannot find the image. 
I've checked the dockerhub of eqmtt-bench and image does exist.
Have no clue about this error.
Thanks in advance:)

note:
docker version:
Docker version 20.10.21, build baeda1f
environment: ubuntu 20.04

**Comment by zmstone** [comment]
Hi @jumpingliu 

If you build the docker image locally (by executing `make docker`), you should not need to pull it.
and the version tag is not `latest`, it's the printout of `git describe --tags --always`
https://github.com/emqx/emqtt-bench/blob/249f7f8a3148e1f329b23af45b909edfbe9f3b95/Makefile#L31


There is however, indeed a docker image pushed to dockerhub: `docker pull emqx/emqtt-bench:latest`
If you do not have any specific needs, this image should work for you.
I will check with my colleagues to understand why and how the image is pushed with a different tag, 
and we will try to automate the docker push to dockerhub and update the README documents to use the new image tag.

**Comment by jumpingliu** [comment]
@zmstone thanks for the reply, problem solved:)
