### ISSUE TITLE
ssh终端关掉就mqtt连接自动退出了，无法在后台运行

### ISSUE THREAD

**Issue by ivanhxq** [emqx/emqtt-bench#201]
问题：
通过ssh连接主机，执行命令如下：
./emqtt_bench sub -h ip_addess -p 1883 -c 7500 -i 10 -t bench1/%i -q 0 

一旦ssh终端断开，emqtt_bench创建的mqtt连接全部退出了，无法长时间测试
试过加参数:--log_to null，也没有

期望：emqtt_bench创建的mqtt连接能在后台运行，即使终端如ssh断开也不退出，用于长时间测试

**Comment by tigercl** [comment]
加个 `&` 就可以了：

```
emqtt_bench &
```

需要日志的话可以这样：

```
emqtt_bench > log.file 2>&1  &
```

**Comment by ivanhxq** [comment]
这样才行:nohub emqtt_bench &
tks
