### ISSUE TITLE
error:~/emqtt-bench$ make /home/deploy/emqtt-bench/scripts/ensure-rebar3.sh 3.19.0-emqx-1 /home/deploy/emqtt-bench/rebar3 compile /usr/bin/env: ‘escript’: No such file or directory Makefile:12: recipe for target 'compile' failed make: *** [compile] Error 127

### ISSUE THREAD

**Issue by q534953428** [emqx/emqtt-bench#213]
<img width="476" alt="image" src="https://user-images.githubusercontent.com/20254704/227210884-892553f3-551a-411a-9ff6-271d84ba8110.png">

 cd emqtt-bench/
 make

~/emqtt-bench$ make
/home/deploy/emqtt-bench/scripts/ensure-rebar3.sh 3.19.0-emqx-1
/home/deploy/emqtt-bench/rebar3 compile
/usr/bin/env: ‘escript’: No such file or directory
Makefile:12: recipe for target 'compile' failed
make: *** [compile] Error 127

**Comment by q534953428** [comment]
I tried  otp_src_20.3/ and   otp_src_22.3 and it didn't work

**Comment by q534953428** [comment]
<img width="608" alt="image" src="https://user-images.githubusercontent.com/20254704/227496840-6dc8f642-0a0b-4e3c-8827-febe6536c3cb.png">

How do I check?

**Comment by id** [comment]
@q534953428 
how did you install Erlang/OTP?
what does `which erl` say? Could you run `ls` in the directory where you have `erl`?

**Comment by q534953428** [comment]
<img width="598" alt="image" src="https://user-images.githubusercontent.com/20254704/227533758-6f64f690-7bb2-4799-b131-cf8fe14db666.png">

wget http://erlang.org/download/otp_src_22.3.tar.gz
tar xzf otp_src_22.3.tar.gz
cd otp_src_22.3
./configure --prefix=/home/erlang   --without-javac  
make & make install
ln -s /home/erlang/bin/erl /usr/local/bin/erl
export PATH=$PATH:/home/erlang/bin

**Comment by thalesmg** [comment]
Does your distribution have Erlang available? It might be simpler to install from that.

Also, note that OTP 22 is quite old by now, emqtt-bench supports OTP 24 and higher.

**Comment by q534953428** [comment]
> 你的发行版有 Erlang 可用吗？从那里安装可能更简单。
> 
> 另外请注意，OTP 22 现在已经很老了，emqtt-bench 支持 OTP 24 及更高版本。

ok,我试试OTP 24

**Comment by q534953428** [comment]
A new error message has been reported

Submodule path 'submodules/openssl/wycheproof': checked out '2196000605e45d91097147c9c71f26b72af58003'
./build.sh: 18: ./build.sh: cmake: not found
Makefile:11: recipe for target 'build-nif' failed
make[1]: *** [build-nif] Error 127
make[1]: Leaving directory '/home/deploy/emqtt-bench/_build/default/lib/quicer'
===> Hook for compile failed!

Makefile:12: recipe for target 'compile' failed
make: *** [compile] Error 1

<img width="777" alt="image" src="https://user-images.githubusercontent.com/20254704/227555055-48bc49ba-130a-4615-b067-f3fb2d73b8fd.png">

**Comment by id** [comment]
@q534953428 try this
```
BUILD_WITHOUT_QUIC=1 make
```

**Comment by q534953428** [comment]
> BUILD_WITHOUT_QUIC=1 make

<img width="527" alt="image" src="https://user-images.githubusercontent.com/20254704/227828518-fa60a27a-fd24-4096-baa9-e28959db59ee.png">
Thank you but still fail

**Comment by id** [comment]
@q534953428 it's again the old error about `escript`. How did you manage to solve it previously?

**Comment by id** [comment]
Also if you have docker, it might be easier to build binaries using our docker image. For example, for Debian 11 it will look like this:
```
rm -rf _build
docker run -it --rm -v $(pwd):/w -w /w ghcr.io/emqx/emqx-builder/5.0-33:1.13.4-24.3.4.2-3-debian11 make
```

We have emqx/emqx-builder images available for many different linux distros, see https://github.com/emqx/emqx-builder/pkgs/container/emqx-builder%2F5.0-33/versions?filters%5Bversion_type%5D=tagged.

**Comment by q534953428** [comment]
> @q534953428这又是关于 的旧错误`escript`。你以前是怎么解决的？


The original otp22, now I use the new otp24, the screenshot above

**Comment by id** [comment]
> A new error message has been reported
> 
> Submodule path 'submodules/openssl/wycheproof': checked out '2196000605e45d91097147c9c71f26b72af58003' ./build.sh: 18: ./build.sh: cmake: not found Makefile:11: recipe for target 'build-nif' failed make[1]: *** [build-nif] Error 127 make[1]: Leaving directory '/home/deploy/emqtt-bench/_build/default/lib/quicer' ===> Hook for compile failed!
> 
> Makefile:12: recipe for target 'compile' failed make: *** [compile] Error 1
> 
> <img alt="image" width="777" src="https://user-images.githubusercontent.com/20254704/227555055-48bc49ba-130a-4615-b067-f3fb2d73b8fd.png">

@q534953428 here you don't have problem with escript. How did you solve it?

**Comment by q534953428** [comment]
> 是的我明白。那么你可以在你拥有的 otp24 上运行这个命令吗`escript`？
> 
> ```
> BUILD_WITHOUT_QUIC=1 make`
> ```

<img width="603" alt="image" src="https://user-images.githubusercontent.com/20254704/227931306-f8a7d067-6ca3-40fb-9a66-d7c291321113.png">

**Comment by q534953428** [comment]
> 是的我明白。那么你可以在你拥有的 otp24 上运行这个命令吗`escript`？
> 
> ```
> BUILD_WITHOUT_QUIC=1 make`
> ```



> escript

After an error is reported, it is an old error

**Comment by id** [comment]
@q534953428 

The problem is that you linked `erl` to /usr/local/bin, but not the rest of erlang binaries.
```
ln -s /home/erlang/bin/erl /usr/local/bin/erl
```

Try this:
```
export PATH=$PATH:/home/erlang/bin
BUILD_WITHOUT_QUIC=1 make
```

**Comment by q534953428** [comment]
No, I guess I'll have to use docker. Thank you

**Comment by q534953428** [comment]
换成dorker后可以，我想可能master代码有些兼容问题。谢谢回答
