### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by Estheriii** [emqx/emqtt-bench#237]
run docker build -t xxxx .
with dockerfile
`ARG FROM=ghcr.io/emqx/emqx-builder/5.0-31:1.13.4-24.3.4.2-2-debian11
FROM ${FROM}
COPY . /emqtt_bench
WORKDIR /emqtt_bench
RUN make compile
ENTRYPOINT ["/emqtt_bench/emqtt_bench"]
CMD [""]`
comes error
`escript: exception error: undefined function rebar3:main/1
  in function  escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
make: *** [Makefile:12: compile] Error 127
`
how can i fix it?

**Comment by id** [comment]
@Estheriii I submitted a patch, as a quick workaround you can build it like this:

```
docker build -t emqtt_bench:mytag --build-arg "FROM=ghcr.io/emqx/emqx-builder/5.2-7:1.15.7-25.3.2-2-debian11" .
```
