### ISSUE TITLE
Parameter setting of ca certificate is not supported

### ISSUE THREAD

**Issue by bagpipes924** [emqx/emqtt-bench#243]
When doing two-way authentication, parameters are not supported to be passed to the CA, and whether domain name verification is required.
![image](https://github.com/emqx/emqtt-bench/assets/11797401/4bb40354-3bda-41e5-a769-7c3d4f5df50c)

**Comment by zmstone** [comment]
validating server certificate in a benchmark tool makes little sense.
you want to use all the resource to test the server instead.

put the certificate chain in `certfile`: client certificate being the first, followed by intermediate CA cert and so on, all the way up to the root certificate (root is optional).
