### ISSUE TITLE
980 connection limit

### ISSUE THREAD

**Issue by akau16** [emqx/emqtt-bench#245]
I used emqtt_bench to stress test my EMQX Server, but found a strange phenomenon.
After rebooting EC2, I used emqtt_bench conn every time for 1,000 transactions, and there was no problem several times.
But as long as I restart EMQX, the number of connections can only reach 980 (the same in every test), and what happens next
"waiting for connack" error message (as shown below), does anyone know about this situation?

![image](https://github.com/emqx/emqtt-bench/assets/142989471/0548d57e-87fa-4726-95b0-5a492a54ad04)

**Comment by zmstone** [comment]
Hi @akau16 
It would be helpful if you can provide the configurations and logs from EMQX.
And monitoring data as well, such as CPU and RAM etc.

**Comment by qzhuyan** [comment]
you have none responsive broker. 
Connection timeout after 1min, I don't think it is emqtt bench's issue.
