### ISSUE TITLE
client(1): discarded unknown message {'DOWN', #Ref<0.3770416882.2094006274.40>, process,<0.78.0>,noproc}

### ISSUE THREAD

**Issue by 2-ming** [emqx/emqtt-bench#255]
When i use `emqtt-bench pub -t "topic/1" -c 5 -w` will report the error of the title, what's the reason

**Comment by 2-ming** [comment]
Is the -w parameter used correctly?

**Comment by id** [comment]
the error in the title is most likely harmless

**Comment by 2-ming** [comment]
When the number of connections is large, use the -w parameter, there will always be several such errors reported, and the number of messages published per second will be correspondingly less.
