### ISSUE TITLE
emqtt-bench可以测试新建连接速率吗

### ISSUE THREAD

**Issue by jiawen94** [emqx/emqtt-bench#264]
我想每个创建的连接立刻断开，测试每秒能够新建多少连接数。emqt-bench是否支持这种场景？我改了-k参数没有效果

**Comment by id** [comment]
Yes, for example
```
emqtt_bench conn --connrate 5000
```

**Comment by qzhuyan** [comment]
目前还不支持，如果你写英语的话 我们的同事可能更能精准理解你的问题。

It is not supported yet. If you write in English, our colleagues may be able to understand your question more accurately.

**Comment by qzhuyan** [comment]
I think we could wrap with bash `until` loop to simulate the client reconnections. 

```
# reconnect 1000 publisher every 30 secs with persistent sessions.
until timeout 30 ./emqtt_bench pub  -c 1000   --prefix AA  -x 3000; do echo `date` ; done
```
