### ISSUE TITLE
Hello, I can't compile this.

### ISSUE THREAD

**Issue by Zziwen** [emqx/emqtt-bench#45]
![4th dmb 40yh3q22q0 36pp](https://user-images.githubusercontent.com/46589682/51021139-a3a3cf00-15bb-11e9-8cd6-09c8d7149e94.png)

**Comment by deepaksood619** [comment]
I am using this docker image directly. It is working great. Hope this helps for now, https://hub.docker.com/r/rkosyk/emqtt-benchmark/

**Comment by dongweiq** [comment]
me too
![image](https://user-images.githubusercontent.com/6800717/54657385-2f7a3000-4b04-11e9-9cdc-6cb237465437.png)

**Comment by Gilbert-Wong** [comment]
Hello, I'm so sorry to tell you guys that this project will not be maintained. And if you want to build this project, you need to install rebar3 via referring this [guide](https://www.rebar3.org/docs/getting-started).

execute commands below. It should be ok.
```
$ git clone https://github.com/erlang/rebar3.git
$ cd rebar3
$ ./bootstrap
$ ./rebar3 local install
```

Last but not least, I suggest you guys to use solution provided by [esl](https://www.erlang-solutions.com/resources/download.html) to install erlang.

**Comment by LittleWoodCover** [comment]
> me too
> ![image](https://user-images.githubusercontent.com/6800717/54657385-2f7a3000-4b04-11e9-9cdc-6cb237465437.png)

have you resolve your problem ?cause i've the same one that you did?

**Comment by googlefan** [comment]
try this . :
wget http://erlang.org/download/otp_src_22.0.tar.gz
### 在下载目录中对.tar.gz进行解压
tar -xzvf otp_src_22.0.tar.gz
### 安装依赖包（安装必须用到的）
yum install -y gcc gcc-c++ unixODBC-devel openssl-devel ncurses-devel
### 进入到解压好的目录中，比如在erlang中解压要进到erlang/otp_src_22.0中设定安装位置
./configure --prefix=/opt/apps/erlang/otp_src_22.0 --without-javac
### 安装
make && make install
### 添加环境变量
vi ~/.base_profile
### 加到原有变量之后使用:隔开,{erlang/bin} 是你的安装路径,如:/opt/apps/erlang/otp_src_22.0/bin
PATH=$PATH:{erlang/bin}
export PATH
:wq
### 使之生效
source ~/.base_profile
### 或者使用软连接方式
ln -s /opt/apps/erlang/otp_src_22.0/bin/erl /usr/bin/erl
