### ISSUE TITLE
shutdown,eaddrnotavail

### ISSUE THREAD

**Issue by qiannianshaonian** [emqx/emqtt-bench#47]
I am trying to connect to 50000 connections to emqttd. But after 27003 connections i am getting client    EXIT: {shutdown,eaddrnotavail}

**Comment by turtleDeng** [comment]
Already fixed, please use the latest version.

**Comment by ArpitSohar** [comment]
Hi @turtleDeng 
Getting the same error while using the latest version. After 1.9L connections on 8Core 64GB machine.
