### ISSUE TITLE
make error!

### ISSUE THREAD

**Issue by winfi89** [emqx/emqtt-bench#50]
After installed erlang,when i make this project.ocurred such error:

**Comment by winfi89** [comment]
home/bench/emqtt_benchmark# make
rebar3 unlock
make: rebar3: Command not found
Makefile:11: recipe for target 'unlock' failed

**Comment by winfi89** [comment]
so,i installed rebar3. But it still not success.

**Comment by winfi89** [comment]
Solved

**Comment by Gilbert-Wong** [comment]
I have integrated rebar3 into this project. Now nobody has to install rebar3 on the local machine.
