### ISSUE TITLE
/emqtt_bench sub -c 1 -i 10 -t bench/%i -q 2

### ISSUE THREAD

**Issue by cuieng123** [emqx/emqtt-bench#56]
The error is as follows
2019-07-30 19:36:52.391 [error] 127.0.0.1:46612 [Channel] Parse failed for function_clause

                 Stacktrace:[{emqx_frame,parse_packet,
                                 [{mqtt_packet_header,4,false,3,true},
                                  <<"T /mqtt HTTP/1.1\r\nhost: localhost:1883\r\nconnection: upgrade\r\nupgrade:">>,
                                  #{max_size => 1048576,version => 4}],
                                 [{file,
                                      "/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_frame.erl"},
                                  {line,147}]},
                             {emqx_frame,parse_frame,4,
                                 [{file,
                                      "/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_frame.erl"},
                                  {line,126}]},
                             {emqx_channel,process_incoming,3,
                                 [{file,
                                      "/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_channel.erl"},
                                  {line,408}]},
                             {gen_statem,call_state_function,5,
                                 [{file,"gen_statem.erl"},{line,1660}]},
                             {gen_statem,loop_event_state_function,6,
                                 [{file,"gen_statem.erl"},{line,1023}]},
                             {proc_lib,init_p_do_apply,3,
                                 [{file,"proc_lib.erl"},{line,249}]}]
Error data:<<"GET /mqtt HTTP/1.1\r\nhost: localhost:1883\r\nconnection: upgrade\r\nupgrade: websocket\r\nsec-websocket-version: 13\r\nsec-websocket-key: x4/aMGKzxeci3YFfWGuI9w==\r\nsec-websocket-protocol: mqtt\r\ncache-control: no-cache\r\n\r\n">>

**Comment by gilbertwong96** [comment]
Thanks for your feedback, now it has been fixed. https://github.com/emqx/emqtt-bench/pull/57/files
