### ISSUE TITLE
escript: exception error: undefined function counters:new/2   

### ISSUE THREAD

**Issue by YangJessie** [emqx/emqtt-bench#58]
Hi! I met this problem after finishing "make" process: 

escript: exception error: undefined function counters:new/2
  in function  emqtt_bench:init/0 (/app/install/emqtt_benchmark/emqtt-bench/src/emqtt_bench.erl, line 176)
  in call from emqtt_bench:start/2 (/app/install/emqtt_benchmark/emqtt-bench/src/emqtt_bench.erl, line 167)
  in call from escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 

I've installed erlang/OTP 21.0 and rebar3.

**Comment by xujunxing1991** [comment]
我也是报错这个！

**Comment by turtleDeng** [comment]
You should install erlang version 21.2 first .
