### ISSUE TITLE
DEFAULT FORMATTER CRASHEDDEFAULT

### ISSUE THREAD

**Issue by shashankel** [emqx/emqtt-bench#63]
REPORT_CB/2 CRASH: #{label => {proc_lib,crash},
                     report =>
                      [[{initial_call,{emqtt,init,['Argument__1']}},
                        {pid,<0.620.0>},
                        {registered_name,[]},
                        {error_info,
                         {error,undef,
                          [{sys,get_log,[[]],[]},
                           {gen_statem,error_info,7,
                            [{file,"gen_statem.erl"},{line,2195}]},
                           {gen_statem,terminate,7,
                            [{file,"gen_statem.erl"},{line,2174}]},
                           {proc_lib,init_p_do_apply,3,
                            [{file,"proc_lib.erl"},{line,249}]}]}},
                        {ancestors,[<0.619.0>]},
                        {message_queue_len,1},
                        {messages,[{'EXIT',<0.619.0>,normal}]},
                        {links,[]},
                        {dictionary,[]},
                        {trap_exit,true},
                        {status,running},
                        {heap_size,987},
                        {stack_size,27},
                        {reductions,1544}],
                       []]}; Reason: {error,undef,
                                      [{erl_error,format_exception,
                                        [5,error,undef,
                                         [{sys,get_log,[[]],[]},
                                          {gen_statem,error_info,7,
                                           [{file,"gen_statem.erl"},
                                            {line,2195}]},
                                          {gen_statem,terminate,7,
                                           [{file,"gen_statem.erl"},
                                            {line,2174}]},
                                          {proc_lib,init_p_do_apply,3,
                                           [{file,"proc_lib.erl"},
                                            {line,249}]}],
                                         #Fun<proc_lib.0.36012461>,
                                         #Fun<proc_lib.1.36012461>,utf8],
                                        []},
                                       {proc_lib,format_exception,4,
                                        [{file,"proc_lib.erl"},{line,851}]},
                                       {proc_lib,format_rep,3,
                                        [{file,"proc_lib.erl"},{line,830}]},
                                       {proc_lib,format_rep,3,
                                        [{file,"proc_lib.erl"},{line,833}]},
                                       {proc_lib,format_rep,3,
                                        [{file,"proc_lib.erl"},{line,828}]},
                                       {proc_lib,format_report,3,
                                        [{file,"proc_lib.erl"},{line,815}]},
                                       {proc_lib,do_format,2,
                                        [{file,"proc_lib.erl"},{line,793}]}]}
DEFAULT FORMATTER CRASHEDDEFAULT FORMATTER CRASHEDDEFAULT FORMATTER CRASHEDDEFAULT FORMATTER CRASHED^C

**Comment by xyz361** [comment]
Hi shashankel ,
If you use benchmark , you should install erlang version 21.2 first .

**Comment by spring2maz** [comment]
Agree with @xyz361, closing this issue.
