### ISSUE TITLE
publish error - einval

### ISSUE THREAD

**Issue by googlefan** [emqx/emqtt-bench#64]
`client(71): publish error - einval
=ERROR REPORT==== 10-Sep-2019::14:56:20.014672 ===
** State machine <0.164.0> terminating
** Last event = {{call,{<0.163.0>,#Ref<0.2879060264.781713413.155584>}},
                 {publish,{mqtt_msg,0,false,false,undefined,<<"bench/71">>,
                                    #{},
                                    <<0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                      0,0,0,0,0,0,0,0,0>>}}}
** When server state  = {connected,
                            {state,undefined,<0.163.0>,undefined,
                                "47.*.*.*",1883,[],emqtt_sock,#Port<0.64>,
                                [],60000,false,
                                <<"zhuhuis-MacBook-Pro_bench_pub_71_4191079359">>,
                                true,undefined,undefined,5,<<"MQTT">>,300,
                                #Ref<0.2879060264.781713411.121982>,false,
                                false,false,
                                {mqtt_msg,0,false,false,undefined,undefined,
                                    undefined,undefined},
                                #{'Maximum-Packet-Size' => 1048576,
                                  'Retain-Available' => 1,
                                  'Shared-Subscription-Available' => 1,
                                  'Subscription-Identifier-Available' => 1,
                                  'Topic-Alias-Maximum' => 0,
                                  'Wildcard-Subscription-Available' => 1},
                                [],#{},infinity,#{},#{},true,30000,undefined,
                                0,undefined,0,524,
                                {none,#{max_size => 268435455,version => 5}}}}
** Reason for termination = exit:einval
** Callback mode = state_functions
** Stacktrace =
**  [{gen_statem,loop_state_callback_result,11,
                 [{file,"gen_statem.erl"},{line,1292}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]
** Client <0.163.0> stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,167}]},
    {gen_statem,call_dirty,4,[{file,"gen_statem.erl"},{line,611}]},
    {emqtt_bench,loop,4,
                 [{file,"/Users/zhuhui/Desktop/emqx/emqtt_benchmark/src/emqtt_bench.erl"},
                  {line,307}]}]`
cn:当我 使用 emqtt_benchmark 做 压测， 10个客户端以每秒100条来发布消息  ，出现这样的错误日志。我不明白为什么会提示这个？
en:When I use emqtt_benchmark to test emqtt service's profile,I got this error log.I want to know why this happen.
![image](https://user-images.githubusercontent.com/3354782/64598534-7a596e00-d3ea-11e9-85a0-85ed7579f8fa.png)

**Comment by tigercl** [comment]
Can you provide complete emqtt_bench command and the details about your subscirption?

**Comment by googlefan** [comment]
> Can you provide complete emqtt_bench command and the details about your subscirption?

 ./emqtt_bench pub -h 47.75.173.20 -p 1883 -c 10 -I 10 -t topic -s 256 

subscirption ：  mosquitto_sub -h 47.75.173.20 -p 1883 -t topic -q 2

**Comment by tigercl** [comment]
I tried your commands but there was nothing wrong with it. Have you changed the configuration of emqx? And maybe you could check your network environment.

**Comment by googlefan** [comment]
> I tried your commands but there was nothing wrong with it. Have you changed the configuration of emqx? And maybe you could check your network environment.

Maybe  my network environmen is not good enough.I try now and this time success.
