### ISSUE TITLE
please recompile this module with an R16B03-1 compiler

### ISSUE THREAD

**Issue by googlefan** [emqx/emqtt-bench#65]
when I make ，the error come up:
`/root/emqtt_benchmark/rebar3 unlock

=ERROR REPORT==== 11-Sep-2019::11:08:46 ===
beam/beam_load.c(1682): Error loading module rebar_utils:
  This BEAM file was compiled for a later version of the run-time system than R16B03-1.
  To fix this, please recompile this module with an R16B03-1 compiler.
  (Use of opcode 154; this emulator supports only up to 153.)

=ERROR REPORT==== 11-Sep-2019::11:08:46 ===
Loading of /root/emqtt_benchmark/rebar3/rebar/ebin/rebar_utils.beam failed: badfile
Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
Uncaught error: undef
Stack trace to the error location:
[{rebar_utils,set_httpc_options,[],[]},
 {rebar3,init_config,0,
         [{file,"/opt/rebar3-3.11.1/src/rebar3.erl"},{line,197}]},
 {rebar3,run,1,[{file,"/opt/rebar3-3.11.1/src/rebar3.erl"},{line,100}]},
 {rebar3,main,1,[{file,"/opt/rebar3-3.11.1/src/rebar3.erl"},{line,66}]},
 {escript,run,2,[{file,"escript.erl"},{line,747}]},
 {escript,start,1,[{file,"escript.erl"},{line,277}]},
 {init,start_it,1,[]},
 {init,start_em,1,[]}]
When submitting a bug report, please include the output of `rebar3 report "your command"`
make: *** [unlock] Error 1`

My envirment is Centos .

**Comment by googlefan** [comment]
I reinstall erlang reslove this problem.I upgrade erlang from R16 to Erlang/OTP R21.2+.

**Comment by turtleDeng** [comment]
Requires Erlang/OTP R21.2+ to build.

**Comment by yilezhu** [comment]
> I reinstall erlang reslove this problem.I upgrade erlang from R16 to Erlang/OTP R21.2+.

how to reinstall?
