### ISSUE TITLE
Why I use "make"  but dont   succeed 

### ISSUE THREAD

**Issue by isZsan** [emqx/emqtt-bench#67]
# make
/mqtt_app/emqtt-bench/rebar3 unlock
/usr/bin/env: escript: No such file or directory
make: *** [unlock] Error 127

#ll  /usr/bin/env
lrwxrwxrwx 1 root root 13 Mar 26  2019 /usr/bin/env -> ../../bin/env*

**Comment by gilbertwong96** [comment]
You have to install erlang/otp on your local machine first and then set the right path environment.

Gilbert Wong

**Comment by isZsan** [comment]
> You have to install erlang/otp on your local machine first and then set the right path environment. Gilbert Wong
> […](#)
> On Oct 14, 2019, 13:55 +0800, isZsan ***@***.***>, wrote: make /mqtt_app/emqtt-bench/rebar3 unlock /usr/bin/env: escript: No such file or directory make: *** [unlock] Error 127 #ll /usr/bin/env lrwxrwxrwx 1 root root 13 Mar 26 2019 /usr/bin/env -> ../../bin/env* — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

yes , I get it , think u
