### ISSUE TITLE
Is MQTTv3 supported?

### ISSUE THREAD

**Issue by amrx101** [emqx/emqtt-bench#78]

**Comment by HJianBo** [comment]
Yes it is

**Comment by HJianBo** [comment]
You can use the `--version` or `-V` to set the MQTT protocol version:
```
  -V, --version      mqtt protocol version: 3 | 4 | 5 [default: 5]
```

But the option just supported in the `./emqtt_bench sub` and `./emqtt_bench pub`  command. We will add it to the `./emqtt_bench conn` at next version.

Thanks @amrx101

**Comment by promission** [comment]
> ```
>   -V, --version      mqtt protocol version: 3 | 4 | 5 [default: 5]
> ```
> 
> You can use the `--version` or `-V` to set the MQTT protocol version. E.g: set MQTT 3.0 by `--version 3`
> 
> But the option just supported in the `./emqtt_bench sub` and `./emqtt_bench pub` command. We will add it to the `./emqtt_bench conn` at next version.
> 
> Thanks @amrx101

Hello, I want to test the emqttv2.3.11 version, which version of the client do I need to install?

**Comment by promission** [comment]
@HJianBo   error info:
make
WARN:  /root/emqtt-bench-0.2/deps/emqttc/src/emqtt.app.src has application id emqtt; expected emqttc
WARN:  Expected /root/emqtt-bench-0.2/deps/getopt to be an app dir (containing ebin/*.app), but no .app found.
==> emqtt-bench-0.2 (get-deps)
WARN:  /root/emqtt-bench-0.2/deps/emqttc/src/emqtt.app.src has application id emqtt; expected emqttc
WARN:  Expected /root/emqtt-bench-0.2/deps/getopt to be an app dir (containing ebin/*.app), but no .app found.
WARN:  /root/emqtt-bench-0.2/deps/emqttc/src/emqtt.app.src has application id emqtt; expected emqttc
ERROR: Dependency dir /root/emqtt-bench-0.2/deps/emqttc failed application validation with reason:
{name_mismatch,{"/root/emqtt-bench-0.2/deps/emqttc/src/emqtt.app.src",
                {expected,emqttc},
                {has,emqtt}}}.
ERROR: 'get-deps' failed while processing /root/emqtt-bench-0.2: rebar_abort
make: *** [get-deps] Error 1
