### ISSUE TITLE
make failed, hot to fix it ?

### ISSUE THREAD

**Issue by KerryJava** [emqx/emqtt-bench#81]
make operation failed

===> Verifying dependencies...
===> Analyzing applications...
===> Compiling emqtt_bench
===> Compiling src/emqtt_bench.erl failed
src/emqtt_bench.erl:398: ssl:cipher_suites/1 is deprecated and will be removed in OTP 24; use use cipher_suites/2,3 instead

make: *** [compile] 错误 1
[jet@192 emqtt-bench]$ 

erlang version:

[jet@192 ~]$ erl
Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]

Eshell V11.0.3  (abort with ^G)

**Comment by ustccq** [comment]
修复有用，还是去扒了fork repo的commit才找着😒。

**Comment by ustccq** [comment]
编译能过，but emqtt_bench pub直接就Error报到这块的错了，弃坑：

=ERROR REPORT==== 13-Oct-2020::08:50:39.628398 ===
Error in process <0.30108.0> with exit value:
{function_clause,[{ssl,supported_suites,[2,3],[{file,"ssl.erl"},{line,1553}]},
                  {ssl,cipher_suites,2,[{file,"ssl.erl"},{line,1064}]},
                  {emqtt_bench,ssl_opts,2,
                               [{file,"/opt/emqtt_benchmark/src/emqtt_bench.erl"},
                                {line,398}]},
                  {emqtt_bench,connect,4,
                               [{file,"/opt/emqtt_benchmark/src/emqtt_bench.erl"},
                                {line,302}]}]}

**Comment by HJianBo** [comment]
Hi guys, Please use OTP 22 to compile it.

We will support OTP 23 in the next version
