### ISSUE TITLE
script can't run

### ISSUE THREAD

**Issue by kgdngitfk** [emqx/emqtt-bench#87]
./emqtt_bench conn -c 500 -i 10
escript: exception error: undefined function counters:new/2
  in function  emqtt_bench:init/0 (/data/github/emqtt-bench/src/emqtt_bench.erl, line 218)
  in call from emqtt_bench:start/2 (/data/github/emqtt-bench/src/emqtt_bench.erl, line 209)
  in call from escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3

environment is
./rebar3 version
rebar 3.11.1 on Erlang/OTP 21 Erts 10.0

**Comment by HJianBo** [comment]
Hi @kgdngitfk Please use OTP 22 to compile it

**Comment by cxb1135139661** [comment]
=ERROR REPORT==== 2-Nov-2020::18:01:46.003333 ===
Error in process <0.113.0> with exit value:
{function_clause,[{dtls_v1,corresponding_tls_version,
                           ['tlsv1.3'],
                           [{file,"dtls_v1.erl"},{line,55}]},
                  {dtls_v1,all_suites,1,[{file,"dtls_v1.erl"},{line,41}]},
                  {ssl,cipher_suites,2,[{file,"ssl.erl"},{line,987}]},
                  {emqtt_bench,'-all_ssl_ciphers/0-lc$^0/1-0-',1,
                               [{file,"/opt/emqtt-bench/src/emqtt_bench.erl"},
                                {line,408}]},
                  {emqtt_bench,'-all_ssl_ciphers/0-lc$^0/1-0-',1,
                               [{file,"/opt/emqtt-bench/src/emqtt_bench.erl"},
                                {line,408}]},
                  {emqtt_bench,all_ssl_ciphers,0,
                               [{file,"/opt/emqtt-bench/src/emqtt_bench.erl"},
                                {line,408}]},
                  {emqtt_bench,ssl_opts,2,
                               [{file,"/opt/emqtt-bench/src/emqtt_bench.erl"},
                                {line,398}]},
                  {emqtt_bench,connect,4,
                               [{file,"/opt/emqtt-bench/src/emqtt_bench.erl"},
                                {line,302}]}]}



Hello, how to deal with this error
