### ISSUE TITLE
emqtt_bench can not use all local port

### ISSUE THREAD

**Issue by huanxue-shen** [emqx/emqtt-bench#94]
set the local port range =60000 65535 ;
then i can just establish 2770 connextions；
net.ipv4.ip_local_port_range = 500 65535； 
this config is about 32500 
the command is
./emqtt_bench conn -h IP-u test -P pas -c 50000 -i 10

**Comment by huanxue-shen** [comment]
client(47019): connect error - eaddrnotavail
=ERROR REPORT==== 16-Dec-2020::16:49:56.536596 ===
** State machine <0.6069.0> terminating
** Last event = {{call,{<0.6068.0>,#Ref<0.3783801872.1316749313.221864>}},
                 {connect,emqtt_sock}}
** When server state  = {initialized,
                            {state,undefined,<0.6068.0>,undefined,
                                "10.187.129.229",1883,[],emqtt_sock,undefined,
                                [],60000,false,
                                <<"mqtt-cluster_bench_sub_47019_3175347137">>,
                                true,<<"test">>,<<"123456">>,5,<<"MQTT">>,300,
                                undefined,false,false,false,
                                {mqtt_msg,0,false,false,undefined,undefined,
                                    undefined,undefined},
                                #{},[],#{},infinity,#{},#{},true,30000,
                                undefined,0,undefined,undefined,1,
                                {none,#{max_size => 268435455,version => 5}}}}
** Reason for termination = exit:eaddrnotavail
** Callback mode = state_functions
** Stacktrace =
**  [{gen_statem,loop_state_callback_result,11,
                 [{file,"gen_statem.erl"},{line,1292}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]
** Client <0.6068.0> stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,167}]},
    {gen_statem,call_dirty,4,[{file,"gen_statem.erl"},{line,611}]},
    {emqtt_bench,connect,4,
                 [{file,"/usr/local/emqtt-bench-0.3.1/src/emqtt_bench.erl"},
                  {line,286}]}]

=CRASH REPORT==== 16-Dec-2020::16:49:56.536944 ===
  crasher:
    initial call: emqtt:init/1
    pid: <0.6069.0>
    registered_name: []
    exception exit: eaddrnotavail
      in function  gen_statem:loop_state_callback_result/11 (gen_statem.erl, line 1292)
    ancestors: [<0.6068.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.6068.0>,normal}]
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 12537
  neighbours:

**Comment by HJianBo** [comment]
Hi @huanxue-shen Have you try the latest version for emqtt-bench?

**Comment by qzhuyan** [comment]
already fixed on master branch
