### ISSUE TITLE
-s  payload size [default: 256]  is bytes

### ISSUE THREAD

**Issue by wangchy0927** [emqx/emqtt-bench#97]
hello, I don't quite understand some parameters
`-s, --size             payload size [default: 256]    `

The message is 256 bytes，Is that so?

`sent(193379): total=998025, rate=30238(msg/sec)`

sent(193379) :What does it mean total bytes??

**Comment by HJianBo** [comment]
> -s, --size payload size [default: 256]
> The message is 256 bytes，Is that so?

Yes, the `--size` is the Payload field size of MQTT PUBLISH packet.


> sent(193379): total=998025, rate=30238(msg/sec)

The `193379 ` is the millisecond time interval between prints.
The `998025 ` is the total number of messages sent
