### ISSUE TITLE
emqtt-bench  make  报错

### ISSUE THREAD

**Issue by 757350134** [emqx/emqtt-bench#99]
安装了otp_src_23.2并配置环境变量，进入emqtt-bench文件夹 make时候报了如下错误： 
===> Package not found in any repo: getopt 1.0.1

**Comment by HJianBo** [comment]
Hi @757350134 Sorry the late reply
To compile the code, you need a good network. So much so that you can visit github.com and https://hex.pm

**Comment by 757350134** [comment]
这两个网站都可以访问

**Comment by qzhuyan** [comment]
close due to inactive ticket.
